cmake_minimum_required(VERSION 3.15)

include(proj.conf OPTIONAL RESULT_VARIABLE proj_conf_file)

if(CONFIG_BFLB_BOARD)
    set(BOARD ${CONFIG_BFLB_BOARD})
endif()
if(CONFIG_BFLB_CHIP)
    set(CHIP ${CONFIG_BFLB_CHIP})
endif()
if(CONFIG_BFLB_CPU_ID)
    set(CPU_ID ${CONFIG_BFLB_CPU_ID})
endif()

if(BOARD STREQUAL "ox64")
    set(CHIP "bl808")
elseif(BOARD STREQUAL "m1sdock")
    set(CHIP "bl808")
elseif(BOARD STREQUAL "bl808dk")
    set(CHIP "bl808")
    unset(BOARD_DIR CACHE)
elseif(BOARD STREQUAL "m0sdock")
    set(CHIP "bl616")
elseif(BOARD STREQUAL "bl616dk")
    set(CHIP "bl616")
    unset(BOARD_DIR CACHE)
elseif(BOARD STREQUAL "m0sense")
    set(CHIP "bl702")
endif()

if(CHIP STREQUAL "bl808")
if(NOT CPU_ID)
    set(CPU_ID "m0")
endif()
endif()

if(CPU_ID)
    message(STATUS "BOARD: ${BOARD}, CHIP: ${CHIP}, CPU_ID: ${CPU_ID}")
else()
    message(STATUS "BOARD: ${BOARD}, CHIP: ${CHIP}")
endif()
if(BOARD_DIR)
    message(STATUS "BOARD_DIR: ${BOARD_DIR}")
endif()


find_package(bouffalo_sdk REQUIRED HINTS $ENV{BL_SDK_BASE})
include(${SDK_PATH}/cmake/kconfig.cmake)

add_subdirectory(${SDK_PATH}/bsp/common/ bsp_common)
#add_subdirectory(${SDK_PATH}/components/ components)
